### ISSUE TITLE
[FEATURE] Allow adding an existing user as moderator or co-owner

### ISSUE THREAD

**Issue by TheTincho** [ContributorCovenant/beacon#195]
All contributions, including pull requests, issues, and comments, are governed by our [code of conduct](https://github.com/ContributorCovenant/beacon/blob/release/CODE_OF_CONDUCT.md).

The current UI only allows sending email invites to add moderators, but it is not clear what happens if the person has already registered, and the extra email round-trip seems unnecessary. Plus, the "make co-owner" feature being linked to this seems counterintuitive.

**Comment by CoralineAda** [comment]
If the invited moderator already has an account, they will receive an email inviting them to join the project. Otherwise they will be prompted to create an account and can then accept the invitation.

For security reasons, we can't display a list of existing moderators to invite. Also to prevent abuse, invited moderators cannot be automatically added to a project without their consent.
