### ISSUE TITLE
[FEATURE] Allow reporting by e-mail

### ISSUE THREAD

**Issue by michellesanver** [ContributorCovenant/beacon#206]
In Symfony we currently get reports by e-mail to care@symfony.com, we would like reporters to still be able to e-mail a report, should they choose to. 

My idea was that we could maybe "add external reporter" who gets all communication by e-mail and never has to register to CoC-Beacon.

A worry is that having to register an account might be an additional step a person does not always want. Being able to add a report on their behalf but them still getting the communication via the tool (by e-mail entered by the moderator) so we don't have to communicate in two places would be awesome.

**Comment by CoralineAda** [comment]
Hi Michelle! In thinking through how this would work, it would be simple enough to email the reporter with moderator comments and issue status updates, but how would the reporter respond?

There's currently functionality in place for a moderator to create an issue on a reporter's behalf, which sends an invitation to Beacon to the reporter. In the interest of safety, no details of the issue (including moderator comments/questions) are ever sent by email. In order to correspond with the moderators, the reporter has to first create an account.

How do you see the reporter response working?

**Comment by michellesanver** [comment]
Hi Coraline! 

The way I see it, the most sensitive information is often in the report itself. If that is sent by e-mail, having the rest of the conversation via e-mail does not sound harmful. 

I do not want to be in a situation where someone has a CoC report but does not want to sign up to "another service". They may have a small report and not deem it worth the effort, and we would miss out on some of the small annoyances that people have and miss some context in the community.

I do not know how to best solve this. The reporter response would work similarly to many issue trackers out there, where the e-mail response goes directly to the CoC beacon. 

If we can not have reports via e-mail, there will still be reports via e-mail and people who do not sign up even with an invite, and we would have to handle those manually and then we wouldn't be able to track them in CoC beacon; and we'd have to still have our other location for certain reports.

I hope I'm clear enough in text, if you'd like we can jump on a video chat one of these days to see what the best solution to this problem could be. I'm also happy to help out if need be! :)

**Comment by CoralineAda** [comment]
@michellesanver OK, I've got this working. It's going to be an organization-only feature (since it costs money to support via a 3rd party provider, and organizations will be paying for Beacon.)

If you go to your Organization page, there is a "Other Settings" link in the sidebar. A checkbox there lets you enable reporting by email. Then go to any of your organization's projects, and the email address for reporting will be shown there.

From that point, anyone can submit a report by email. Comments from moderators to reporters will be emailed to the reporter, and the reporter can respond by email. All of the existing reporter chat functionality on the Issue page works as expected.

You can also block an email reporter, just like you can block a regular reporter with a Beacon account.

Feel free to put this through its paces, and let me know if you run into any issues!
